
# secret_key_base has moved to config/credentials.yml.enc (Rails 5.2+)
# To set your secret_key_base, run:
#   bin/rails credentials:edit
# and add:
# development:
#   secret_key_base: super_long_secret_key_for_development
# test:
#   secret_key_base: super_long_secret_key_for_test
